name: App Run β デプロイ

on:
  push:
    branches: main

jobs:
  docker:
    runs-on: alpine-latest
      uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 23

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username:  ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: esunobot.sakuracr.jp/alpine:latest
        secret-envs: |
          TOKEN=${{ secrets.TOKEN }}