name: App Run β デプロイ

on:    
  workflow_dispatch:

permissions:
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
          
      - name: ログイン
        uses: docker/login-action@v3
        with:
          registry: ${{vars.SAKURA_REGISTRY}}
          username:  ${{ vars.SAKURA_USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: チェックアウト
        uses: actions/checkout@v4

      - name: Docker Imageのcreateとプッシュ
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{vars.SAKURA_REGISTRY}}/${{vars.CONTAINER_NAME}}:${{vars.CONTAINER_TAG}}

# https://manual.sakura.ad.jp/api/cloud/apprun/#tag/アプリケーション/operation/postApplication
      - name: AppRunβのデプロイ CONTAINER
        run: |
          curl https://secure.sakura.ad.jp/cloud/api/apprun/1.0/apprun/api/applications/${{vars.SAKURA_APPLICATION_ID}} -X PATCH \
          -u ${{vars.SAKURA_ACCESS_TOKEN}}:${{secrets.SAKURA_ACCESS_TOKEN_SECRET}} \
          -H "Content-Type: application/json" \
          -d '{
            "timeout_seconds": 10,
            "components": [
              {
                "name": "esunobot",
                "max_cpu": "1",
                "max_memory": "2Gi",
                "deploy_source": {
                  "container_registry": {
                    "image": "${{vars.SAKURA_REGISTRY}}/${{vars.CONTAINER_NAME}}:${{vars.CONTAINER_TAG}}",
                    "server": "${{vars.SAKURA_REGISTRY}}",
                    "username": "${{ vars.SAKURA_USERNAME }}",
                    "password": "${{ secrets.PASSWORD }}"
                  }
                },
                "env": [
                  {"key": "TOKEN", "value": "${{ secrets.DISCORD_TOKEN }}"},
                  {"key": "WEBHOOK", "value": "${{secrets.DISCORD_WEBHOOK}}"}
                ]
              }
            ]
          }'
