name: App Run β デプロイ

on:
  push:
    branches: 
      - main

permissions:
  contents: read

jobs:
  push:
    
    runs-on: alpine-latest
    container: node/current-alpine

    steps:
          
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username:  ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: esunobot.sakuracr.jp/alpine:latest
          secret-envs: |
            TOKEN=${{ secrets.TOKEN }}