name: App Run β デプロイ

on:
  push:
    branches: 
      - main
  workflow_dispatch:


permissions:
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
          
      - name: ログイン
        uses: docker/login-action@v3
        with:
          registry: esunobot.sakuracr.jp
          username:  ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: チェックアウト
        uses: actions/checkout@v4

      - name: プッシュ
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: esunobot.sakuracr.jp/alpine:latest